import {StateType} from "./MainList";

export let stateOfWords: Array<StateType> = [

    {enWord: 'embodiment', rusWord: 'воплощение', rusWord2:'олицетворение'},
    {enWord: 'accomplish', rusWord: 'добиться', rusWord2:'достичь'},
    {enWord: 'no way', rusWord: 'ни за что', rusWord2:'да ладно'},
    {enWord: 'essential', rusWord: 'необходимо', rusWord2:'важно'},
    {enWord: 'to slam', rusWord: 'хлопнуть', rusWord2:'швырнуть'},
    {enWord: 'somehow', rusWord: 'некторым образом', rusWord2:'так или иначе'},
    {enWord: 'box office', rusWord: 'касса', rusWord2:'кассовые сборы'},
    {enWord: 'assume', rusWord: 'предположить', rusWord2:'взять на себя'},
    {enWord: 'egos', rusWord: 'эго', rusWord2:'самолюбие'},
    {enWord: 'to collaborate', rusWord: 'сотрудничать', rusWord2:'взаимодействовать'},
    {enWord: 'contradiction', rusWord: 'противоречие', rusWord2:'несоответствие'},
    {enWord: 'split up with...', rusWord: 'расстоваться с ...', rusWord2:'разводиться с ...'},
    {enWord: 'interrogation', rusWord: 'допрос', rusWord2:'дознание'},
    {enWord: 'to swarm', rusWord: 'роиться', rusWord2:'толпиться', rusWord3:'заполнять'},
    {enWord: 'expand on a subject', rusWord: 'распространяться на тему', rusWord2:'подробнее на эту тему'},
    {enWord: 'degree', rusWord: 'градус', rusWord2:'диплом', rusWord3:'научная степень'},
    {enWord: 'to consider', rusWord: 'рассмотреть', rusWord2:'учесть', rusWord3:'предусмотреть'},
    {enWord: 'struggle', rusWord: 'борьба', rusWord2:'драка', rusWord3:'битва'},
    {enWord: 'appearance', rusWord: 'появление', rusWord2:'внешний вид', rusWord3:'матч'},
    {enWord: 'hurt', rusWord: 'вред'},
    {enWord: 'to share', rusWord: 'делить'},
    {enWord: 'detached house', rusWord: 'отдельный дом'},
    {enWord: 'residential area', rusWord: 'жилой район'},
    {enWord: 'hot air balloon', rusWord: 'воздушный шар'},
    {enWord: 'for your record', rusWord: 'к твоему сведению'},
    {enWord: 'it doesn`t matter', rusWord: 'без разницы', rusWord2:'не имеет значения'},
    {enWord: 'it`s up to you', rusWord: 'тебе решать'},
    {enWord: 'let`s give it a shot', rusWord: 'давай попробуем'},
    {enWord: 'cinnamon rolls', rusWord: 'булочки с корицей'},
    {enWord: 'give it up', rusWord: 'встречайте', rusWord2:'приветствуйте'},
    {enWord: 'affordable', rusWord: 'доступный', rusWord2:'приемлемый'},
    {enWord: 'sucker punch', rusWord: 'удар из под тишка'},
    {enWord: 'pickle juice', rusWord: 'рассол'},
    {enWord: 'outskirts', rusWord: 'отшиб города'},
    {enWord: 'suburb', rusWord: 'пригород'},
    {enWord: 'rush hour', rusWord: 'час пик'},
    {enWord: 'contemporary', rusWord: 'современный'},
    {enWord: 'picturesque', rusWord: 'живописный'},
    {enWord: 'fascinating', rusWord: 'очаровательный'},
    {enWord: 'inner cities', rusWord: 'центр города'},
    {enWord: 'conveniently located', rusWord: 'удобно расположен'},
    {enWord: 'overcrowded', rusWord: 'перенаселен'},
    {enWord: 'apartment blocks', rusWord: 'многоквартирный дом'},
    {enWord: 'get mortgages', rusWord: 'взять ипотеку'},
    {enWord: 'to drop somebody off', rusWord: 'высадить кого-либо'},
    {enWord: 'self-catering accommodation', rusWord: 'жилье с самообслуживанием'},
    {enWord: 'to get around the city', rusWord: 'передвигаться по городу'},
    {enWord: 'in the off-season', rusWord: 'вне сезона'},
    {enWord: 'local crafts', rusWord: 'местные сувениры'},
    {enWord: 'on your own', rusWord: 'самостоятельно'},
    {enWord: 'stopover', rusWord: 'остановка'},
    {enWord: 'dumplings', rusWord: 'пельмени'},
    {enWord: 'it`s grossing me out', rusWord: 'это выводит меня из себя'},
    {enWord: 'marshmallow', rusWord: 'зефир'},
    {enWord: 'to put up with', rusWord: 'мириться с чем-то'},
    {enWord: 'to pay off mortgages', rusWord: 'выплатить ипотеку'},
    {enWord: 'to get stuck in a traffic jam', rusWord: 'застрять в пробке'},
    {enWord: 'hectic', rusWord: 'суматошный',rusWord2:'напряженный'},
    {enWord: 'to pick up', rusWord: 'подобрать',rusWord2:'забрать'},
    {enWord: 'get off your high horse', rusWord: 'спустись с небес на землю'},
    {enWord: 'chanterelle', rusWord: 'лисички'},
    {enWord: 'I`ll see you around', rusWord: 'увидимся'},
    {enWord: 'What is it to me', rusWord: 'Какое мне до этого дело'},
    {enWord: 'have a lot in common', rusWord: 'много общего'},
    {enWord: 'get on well with somebody', rusWord: 'ладить с кем-либо'},
    {enWord: 'keep in touch with', rusWord: 'поддерживать отношения'},
    {enWord: 'strained relations', rusWord: 'натянутые отношения'},
    {enWord: 'warm relations', rusWord: 'теплые отношения'},
    {enWord: 'family gathering', rusWord: 'семейные встречи'},
    {enWord: 'household chores', rusWord: 'работа по дому'},
    {enWord: 'to charge somebody rent', rusWord: 'брать плату за проживание'},
    {enWord: 'well-behaved', rusWord: 'воспитанный'},
    {enWord: 'I don`t wanna overstay my welcome', rusWord: 'я не хочу злоупотреблять твоим гостепреимством'},
    {enWord: 'Could you be more specific?', rusWord: 'Можно поконкретнее?'},
    {enWord: 'Don`t be mad at me', rusWord: 'Не сердись на меня'},
    {enWord: 'I don`t wanna put you in the middle of it', rusWord: 'я не хочу тебя впутывать в это'},
    {enWord: 'it`s off the table', rusWord: 'это не обсуждается'},
    {enWord: 'rival', rusWord: 'соперник'},
    {enWord: 'bachelor party', rusWord: 'мальчишник'},
    {enWord: 'long-distance relationships', rusWord: 'отношения на расстоянии'},
    {enWord: 'to go out with', rusWord: 'встречаться с', rusWord2:'иметь отношения с'},
    {enWord: 'naughty', rusWord: 'непослушный', rusWord2:'капризный'},
    {enWord: 'competitive', rusWord: 'конкурентный'},
    {enWord: 'have a crush on each other', rusWord: 'влюбиться друг в друга'},
    {enWord: 'to expand', rusWord: 'расширять'},
    {enWord: 'overcoming', rusWord: 'преодоление'},
    {enWord: 'willing', rusWord: 'готовый',rusWord2:'согласный', rusWord3:'желающий'},
    {enWord: 'ladle', rusWord: 'половник'},
    {enWord: 'colander', rusWord: 'дуршлаг'},
    {enWord: 'cutting board', rusWord: 'разделочная доска'},
    {enWord: 'chopping board', rusWord: 'разделочная доска'},
    {enWord: 'can opener', rusWord: 'консервный нож'},
    {enWord: 'corkscrew', rusWord: 'штопор'},
    {enWord: 'spatula', rusWord: 'лопатка',rusWord2:'лопатка для жарки'},
    {enWord: 'to settle', rusWord: 'решить',rusWord2:'урегулировать'},
    {enWord: 'indomitable', rusWord: 'несгибаемый',rusWord2:'неукротимый'},
    {enWord: 'pull it off', rusWord: 'справиться с этим',rusWord2:'получиться'},
    {enWord: 'modest', rusWord: 'скромный'},
    {enWord: 'glint in the eye', rusWord: 'блеск в глазах'},
    {enWord: 'martial arts', rusWord: 'боевые исскуства'},
    {enWord: 'smirk', rusWord: 'ухмылка'},
    {enWord: 'generous', rusWord: 'щедрый'},
    {enWord: 'gamble', rusWord: 'игра',rusWord2:'риск', rusWord3:'азарт'},
    {enWord: 'selfish', rusWord: 'эгоистичный'},
    {enWord: 'get along with somebody', rusWord: 'ладить с кем-либо'},
    {enWord: 'outgoing people', rusWord: 'общительные люди'},
    {enWord: 'open minded', rusWord: 'широких взглядов'},
    {enWord: 'narrow minded', rusWord: 'узких взглядов'},
    {enWord: 'think outside the box', rusWord: 'думать нестандартно'},
    {enWord: 'reserved person', rusWord: 'закрытый человек'},
    {enWord: 'to achieve goals', rusWord: 'достигать цели'},
    {enWord: 'to mess up', rusWord: 'испортить', rusWord2:'завалить'},
    {enWord: 'book', rusWord: 'книга'},
    {enWord: 'treadmill', rusWord: 'беговая дорожка'},
    {enWord: 'tread', rusWord: 'шаг', rusWord2:'протектор'},
    {enWord: 'keep it together', rusWord: 'держи себя в руках', rusWord2:'сохраняй спокойствие'},
    {enWord: 'indifferent', rusWord: 'различный', rusWord2:'равнодушный'},
    {enWord: 'tread lightly', rusWord: 'действовать осторожно'},
    {enWord: 'to be ambitious', rusWord: 'быть амбициозным'},
    {enWord: 'to work hard on something', rusWord: 'усердно работать над чем-либо'},
    {enWord: 'to miss out', rusWord: 'пропустить'},
    {enWord: 'mental', rusWord: 'психический'},
    {enWord: 'to encourage to do something', rusWord: 'воодушевлять что-то сделать'},
    {enWord: 'to occur', rusWord: 'происходить', rusWord2:'иметь место'},
    {enWord: 'orbital bone', rusWord: 'скуловая кость'},
    {enWord: 'to master different skills', rusWord: 'получать разные навыки'},
    {enWord: 'to focus on something', rusWord: 'сосредоточиться на чем-то',rusWord2:'сконцентрироваться на чем-то'},
    {enWord: 'to beg', rusWord: 'умолять'},
    {enWord: 'corpse', rusWord: 'мертвец'},
    {enWord: 'mortician', rusWord: 'гробовщик'},
    {enWord: 'den', rusWord: 'логово'},
    {enWord: 'thirsty', rusWord: 'жажда'},
    {enWord: 'amusement', rusWord: 'развлечение'},
    {enWord: 'thoughtful', rusWord: 'заботливый'},
    {enWord: 'grumpy', rusWord: 'сварливый'},
    {enWord: 'to scream', rusWord: 'кричать'},
    {enWord: 'screwdriver', rusWord: 'отвертка'},
    {enWord: 'fuse', rusWord: 'предохранитель'},
    {enWord: 'to mend', rusWord: 'исправить'},
    {enWord: 'commitment', rusWord: 'обязательство'},
    {enWord: 'spell out', rusWord: 'сформулировать'},
    {enWord: 'orphan', rusWord: 'сирота'},
    {enWord: 'orphanage', rusWord: 'детский дом'},
    {enWord: 'harebrained', rusWord: 'легкомысленный'},
    {enWord: 'survey', rusWord: 'исследование'},
    {enWord: 'think it over', rusWord: 'обдумать'},
    {enWord: 'to deserve', rusWord: 'заслужить'},
    {enWord: 'slump', rusWord: 'спад'},
    {enWord: 'to wander', rusWord: 'блуждать'},
    {enWord: 'trail', rusWord: 'след'},
    {enWord: 'prairie', rusWord: 'степь'},
    {enWord: 'to keep over', rusWord: 'удерживать'},
    {enWord: 'to ring out', rusWord: 'прозвучать'},
    {enWord: 'valley', rusWord: 'долина'},
    {enWord: 'contraction', rusWord: 'сокращение'},
    {enWord: 'ambien', rusWord: 'снотворное'},
    {enWord: 'awesome', rusWord: 'великолепно'},
    {enWord: 'unresponsive', rusWord: 'без сознания'},
    {enWord: 'affirmative', rusWord: 'позитивный'},
    {enWord: 'malfunction', rusWord: 'неисправность', rusWord2:'поломка'},
    {enWord: 'determination', rusWord: 'определение'},
    {enWord: 'immutable', rusWord: 'неизменный'},
    {enWord: 'immutability', rusWord: 'неизменность'},
    {enWord: 'to terminate', rusWord: 'прервать'},
    {enWord: 'to shatter', rusWord: 'разрушить'},
    {enWord: 'wind', rusWord: 'ветер'},
    {enWord: 'to wind up', rusWord: 'закончить', rusWord2:'занести'},
    {enWord: 'suing', rusWord: 'судиться'},
    {enWord: 'to lash', rusWord: 'хлестать'},
    {enWord: 'lash', rusWord: 'плеть'},
    {enWord: 'to lash out', rusWord: 'наброситься'},
    {enWord: 'closure', rusWord: 'закрытие'},
    {enWord: 'brown-nosing', rusWord: 'подлиза'},
    {enWord: 'scale', rusWord: 'масштаб'},
    {enWord: 'to prosecute', rusWord: 'привлекать к суду'},
    {enWord: 'to parse', rusWord: 'анализировать'},
    {enWord: 'to accuse', rusWord: 'обвинять'},
    {enWord: 'response', rusWord: 'реакция', rusWord2:'ответ'},
    {enWord: 'to show up', rusWord: 'появиться', rusWord2:'явиться', rusWord3:'придти'},
    {enWord: 'pity', rusWord: 'жалость'},
    {enWord: 'bride', rusWord: 'невеста'},
    {enWord: 'to insist', rusWord: 'настаивать', rusWord2:'требовать'},
    {enWord: 'horrendous', rusWord: 'ужасный'},
    {enWord: 'otherwise', rusWord: 'иначе'},
    {enWord: 'curse', rusWord: 'проклятие'},
    {enWord: 'first-grader', rusWord: 'первоклассник'},
    {enWord: 'fictional', rusWord: 'вымышленный'},
    {enWord: 'ransom', rusWord: 'выкуп'},
    {enWord: 'disguise', rusWord: 'маскировка'},
    {enWord: 'make out', rusWord: 'целоваться'},
    {enWord: 'to get away from it all', rusWord: 'сбежать от всего этого'},
    {enWord: 'to set off', rusWord: 'отправиться в путь'},
    {enWord: 'to see somebody off', rusWord: 'проводить кого-либо'},
    {enWord: 'to get on a plane', rusWord: 'сесть в самолет'},
    {enWord: 'to get off the plane', rusWord: 'выйти из самолета'},
    {enWord: 'slightly less', rusWord: 'немного меньше'},
    {enWord: 'What is so funny about that?', rusWord: 'Что в этом смешного?'},
    {enWord: 'The bottom line is that...', rusWord: 'Суть в том...'},
    {enWord: 'entire', rusWord: 'целый'},
    {enWord: 'courageous', rusWord: 'мужественно'},
    {enWord: 'feud', rusWord: 'вражда'},
    {enWord: 'say in private', rusWord: 'сказать наедине'},
    {enWord: 'screw around', rusWord: 'валять дурака'},
    {enWord: 'legislator', rusWord: 'законодатель'},
    {enWord: 'recently', rusWord: 'недавно'},
    {enWord: 'recent', rusWord: 'последний'},
    {enWord: 'to attend', rusWord: 'посещать',rusWord2:'присутствовать' },
    {enWord: 'to expect', rusWord: 'ожидать'},
    {enWord: 'nothing less', rusWord: 'ничего другого'},
    {enWord: 'straightforward', rusWord: 'прямолинейный'},
    {enWord: 'to set deadlines', rusWord: 'установить срок'},
    {enWord: 'to meet deadlines', rusWord: 'уложиться в срок'},
    {enWord: 'to slack off', rusWord: 'расслабиться'},
    {enWord: 'high powered jobs', rusWord: 'высокая должность'},
    {enWord: 'to work in shifts', rusWord: 'работать посменно'},
    {enWord: 'it`s not a big deal', rusWord: 'ничего особенного'},
    {enWord: 'how come?', rusWord: 'Как так вышло?'},
    {enWord: 'to have a burnout', rusWord: 'перегореть'},
    {enWord: 'benefits package', rusWord: 'социальный пакет'},
    {enWord: 'sick leave', rusWord: 'больничный'},
    {enWord: 'maternity leave', rusWord: 'декретный отпуск'},
    {enWord: 'to get stuck behind a desk', rusWord: 'застрять за работой'},
    {enWord: 'I`m fed up', rusWord: 'Я сыт по горло'},
    {enWord: 'get down to', rusWord: 'приступить'},
    {enWord: 'to binge', rusWord: 'напиться', rusWord2:'пьянствовать'},
    {enWord: 'flow state', rusWord: 'состояние потока'},
    {enWord: 'pinkie', rusWord: 'мизинец'},
    {enWord: 'rod', rusWord: 'стержень'},
    {enWord: 'clutch', rusWord: 'тиски'},
    {enWord: 'to clutch', rusWord: 'схватить'},
    {enWord: 'to mutter', rusWord: 'бормотать'},
    {enWord: 'dagger', rusWord: 'кинжал'},
    {enWord: 'trapdoor', rusWord: 'люк'},
    {enWord: 'drizzle', rusWord: 'морось'},
    {enWord: 'rather', rusWord: 'лучше', rusWord2:'довольно'},
    {enWord: 'it`s rather cold', rusWord: 'довольно холодно'},
    {enWord: 'to exclaim', rusWord: 'воскликнуть'},
    {enWord: 'to rub', rusWord: 'тереть'},
    {enWord: 'splendid', rusWord: 'великолепный'},
    {enWord: 'villain', rusWord: 'злодей'},
    {enWord: 'elbow', rusWord: 'локоть'},
    {enWord: 'arsenic', rusWord: 'мышьяк'},
    {enWord: 'to knock', rusWord: 'стучать'},
    {enWord: 'to knock out', rusWord: 'выбить'},
    {enWord: 'ensemble', rusWord: 'ансамбль'},
    {enWord: 'chill', rusWord: 'прохладный'},
    {enWord: 'cave', rusWord: 'пещера'},
    {enWord: 'simmering', rusWord: 'кипение'},
    {enWord: 'toad', rusWord: 'жаба'},
    {enWord: 'he stung with remorse', rusWord: 'Он терзался угрызениями совести'},
    {enWord: 'remorse', rusWord: 'раскаяние',rusWord2:'угрызения совести'},
    {enWord: 'to figure out', rusWord: 'выяснять',rusWord2:'вычислять'},
    {enWord: 'to defy', rusWord: 'игнорировать',rusWord2:'бросать вызов'},
    {enWord: 'smoothly', rusWord: 'гладко',rusWord2:'плавно'},
    {enWord: 'witch', rusWord: 'ведьма',rusWord2:'колдунья'},
    {enWord: 'kettle', rusWord: 'чайник',rusWord2:'котел'},
    {enWord: 'it`s drizzling', rusWord: 'моросит'},
    {enWord: 'incantation', rusWord: 'заклинание'},
    {enWord: 'chain', rusWord: 'цепь'},
    {enWord: 'manfully', rusWord: 'мужественно'},
    {enWord: 'cough', rusWord: 'кашель'},
    {enWord: 'cough it up', rusWord: 'кашляйте'},
    {enWord: 'purpose', rusWord: 'цель'},
    {enWord: 'freak', rusWord: 'ненормальный'},
    {enWord: 'to appreciate', rusWord: 'ценить'},
    {enWord: 'legit', rusWord: 'законный'},
    {enWord: 'fellas', rusWord: 'ребята'},
    {enWord: 'dude', rusWord: 'чувак'},
    {enWord: 'nerve-wracking', rusWord: 'нервотрепка'},
    {enWord: 'shape', rusWord: 'форма'},
    {enWord: 'bonker', rusWord: 'помешательство'},
    {enWord: 'he is bonkers', rusWord: 'он чокнутый'},
    {enWord: 'freak out', rusWord: 'психовать'},
    {enWord: 'footage', rusWord: 'отснятый материал'},
    {enWord: 'to accuse', rusWord: 'обвинять'},
    {enWord: 'to bind', rusWord: 'связывать'},
    {enWord: 'gosh', rusWord: 'черт возьми'},
    {enWord: 'rural', rusWord: 'деревенский'},
    {enWord: 'sprawling', rusWord: 'раскидистый'},
    {enWord: 'accurate', rusWord: 'точный'},
    {enWord: 'rig', rusWord: 'буровая установка'},
    {enWord: 'goatee', rusWord: 'козлиная бородка'},
    {enWord: 'pal', rusWord: 'приятель'},
    {enWord: 'buddy', rusWord: 'приятель'},
    {enWord: 'rough', rusWord: 'грубый'},
    {enWord: 'intentions', rusWord: 'намерения'},
    {enWord: 'gorgeous', rusWord: 'безумной красивая'},
    {enWord: 'asunder', rusWord: 'разделить (пополам, на куски)'},
    {enWord: 'get out of your way', rusWord: 'не буду мешать уйти с пути'},
    {enWord: 'There is a lot to that', rusWord: 'В этом большое значение'},
    {enWord: 'to work under pressure', rusWord: 'работать под давлением'},
    {enWord: 'to compensate travel expenses', rusWord: 'компенсировать расходы на путешествия'},
    {enWord: 'What does this have to do with me?', rusWord: 'Какое отношение это имеет ко мне?'},
    {enWord: 'I wouldn`t be sure about that', rusWord: 'Я бы не был так уверен насчет этого'},
    {enWord: 'equally', rusWord: 'не менее', rusWord2:'также', rusWord3:'одинаково'},
    {enWord: 'to melt', rusWord: 'таять', rusWord2:'плавить', rusWord3:'растопить'},
    {enWord: 'roughneck', rusWord: 'работяга', rusWord2:'рабочий нефтянник', rusWord3:'рабочий буровик'},
    {enWord: 'weird', rusWord: 'странный', rusWord2:'фатальный', rusWord3:'судьбаносный'},
    {enWord: 'chant', rusWord: 'пение', rusWord2:'сказание', rusWord3:'ода'},
    {enWord: 'to spur of the moment', rusWord: 'спонтанно', rusWord2:'пришпоривание момента'},
    {enWord: 'breed', rusWord: 'поколение', rusWord2:'потомство'},
    {enWord: 'foray', rusWord: 'набег', rusWord2:'налет'},
    {enWord: 'whisper', rusWord: 'шорох', rusWord2:'шепот'},
    {enWord: 'to steady', rusWord: 'укреплять', rusWord2:'стабилизировать'},
    {enWord: 'decline', rusWord: 'сокращение', rusWord2:'снижение', rusWord3:'уменьшение'},
    {enWord: 'share', rusWord: 'доля', rusWord2:'акция', rusWord3:'часть'},
    {enWord: 'endorsement', rusWord: 'одобрение', rusWord2:'утверждение', rusWord3:'принятие'},
]