import {StateType} from "./MainList";

export let stateOfWords: Array<StateType> = [

    {enWord: 'embodiment', rusWord: 'воплощение', rusWord2:'олицетворение'},
    {enWord: 'accomplish', rusWord: 'добиться', rusWord2:'достичь'},
    {enWord: 'essential', rusWord: 'необходимо', rusWord2:'важно'},
    {enWord: 'to slam', rusWord: 'хлопнуть', rusWord2:'швырнуть'},
    {enWord: 'somehow', rusWord: 'некторым образом', rusWord2:'так или иначе'},
    {enWord: 'box office', rusWord: 'касса', rusWord2:'кассовые сборы'},
    {enWord: 'assume', rusWord: 'предположить', rusWord2:'взять на себя'},
    {enWord: 'egos', rusWord: 'эго', rusWord2:'самолюбие'},
    {enWord: 'to collaborate', rusWord: 'сотрудничать', rusWord2:'взаимодействовать'},
    {enWord: 'contradiction', rusWord: 'противоречие', rusWord2:'несоответствие'},
    {enWord: 'expand on a subject', rusWord: 'распространяться на тему', rusWord2:'подробнее на эту тему'},
    {enWord: 'degree', rusWord: 'градус', rusWord2:'диплом', rusWord3:'научная степень'},
    {enWord: 'to consider', rusWord: 'рассмотреть', rusWord2:'учесть', rusWord3:'предусмотреть'},
    {enWord: 'struggle', rusWord: 'борьба', rusWord2:'драка', rusWord3:'битва'},
    {enWord: 'appearance', rusWord: 'появление', rusWord2:'внешний вид', rusWord3:'матч'},
    {enWord: 'hurt', rusWord: 'вред'},
    {enWord: 'I don`t wanna overstay my welcome', rusWord: 'я не хочу злоупотреблять твоим гостепреимством'},
    {enWord: 'I don`t wanna put you in the middle of it', rusWord: 'я не хочу тебя впутывать в это'},
    {enWord: 'it`s off the table', rusWord: 'это не обсуждается'},
    {enWord: 'rival', rusWord: 'соперник'},
    {enWord: 'bachelor party', rusWord: 'мальчишник'},
    {enWord: 'competitive', rusWord: 'конкурентный'},
    {enWord: 'to expand', rusWord: 'расширять'},
    {enWord: 'overcoming', rusWord: 'преодоление'},
    {enWord: 'willing', rusWord: 'готовый',rusWord2:'согласный', rusWord3:'желающий'},
    {enWord: 'ladle', rusWord: 'половник'},
    {enWord: 'colander', rusWord: 'дуршлаг'},
    {enWord: 'cutting board', rusWord: 'разделочная доска'},
    {enWord: 'chopping board', rusWord: 'разделочная доска'},
    {enWord: 'can opener', rusWord: 'консервный нож'},
    {enWord: 'corkscrew', rusWord: 'штопор'},
    {enWord: 'spatula', rusWord: 'лопатка',rusWord2:'лопатка для жарки'},
    {enWord: 'to settle', rusWord: 'решить',rusWord2:'урегулировать'},
    {enWord: 'indomitable', rusWord: 'несгибаемый',rusWord2:'неукротимый'},
    {enWord: 'pull it off', rusWord: 'справиться с этим',rusWord2:'получиться'},
    {enWord: 'modest', rusWord: 'скромный'},
    {enWord: 'glint in the eye', rusWord: 'блеск в глазах'},
    {enWord: 'martial arts', rusWord: 'боевые исскуства'},
    {enWord: 'smirk', rusWord: 'ухмылка'},
    {enWord: 'generous', rusWord: 'щедрый'},
    {enWord: 'gamble', rusWord: 'игра',rusWord2:'риск', rusWord3:'азарт'},
    {enWord: 'selfish', rusWord: 'эгоистичный'},
    {enWord: 'get along with somebody', rusWord: 'ладить с кем-либо'},
    {enWord: 'outgoing people', rusWord: 'общительные люди'},
    {enWord: 'open minded', rusWord: 'широких взглядов'},
    {enWord: 'narrow minded', rusWord: 'узких взглядов'},
    {enWord: 'think outside the box', rusWord: 'думать нестандартно'},
    {enWord: 'reserved person', rusWord: 'закрытый человек'},
    {enWord: 'to achieve goals', rusWord: 'достигать цели'},
    {enWord: 'to mess up', rusWord: 'испортить', rusWord2:'завалить'},
    {enWord: 'book', rusWord: 'книга'},
    {enWord: 'treadmill', rusWord: 'беговая дорожка'},
    {enWord: 'tread', rusWord: 'шаг', rusWord2:'протектор'},
    {enWord: 'keep it together', rusWord: 'держи себя в руках', rusWord2:'сохраняй спокойствие'},
    {enWord: 'indifferent', rusWord: 'различный', rusWord2:'равнодушный'},
    {enWord: 'tread lightly', rusWord: 'действовать осторожно'},
    {enWord: 'to be ambitious', rusWord: 'быть амбициозным'},
    {enWord: 'to work hard on something', rusWord: 'усердно работать над чем-либо'},
    {enWord: 'to miss out', rusWord: 'пропустить'},
    {enWord: 'mental', rusWord: 'психический'},
    {enWord: 'to encourage to do something', rusWord: 'воодушевлять что-то сделать'},
    {enWord: 'to occur', rusWord: 'происходить', rusWord2:'иметь место'},
    {enWord: 'orbital bone', rusWord: 'скуловая кость'},
    {enWord: 'to master different skills', rusWord: 'получать разные навыки'},
    {enWord: 'to focus on something', rusWord: 'сосредоточиться на чем-то',rusWord2:'сконцентрироваться на чем-то'},
    {enWord: 'to beg', rusWord: 'умолять'},
    {enWord: 'corpse', rusWord: 'мертвец'},
    {enWord: 'mortician', rusWord: 'гробовщик'},
    {enWord: 'den', rusWord: 'логово'},
    {enWord: 'thirsty', rusWord: 'жажда'},
    {enWord: 'amusement', rusWord: 'развлечение'},
    {enWord: 'thoughtful', rusWord: 'заботливый'},
    {enWord: 'grumpy', rusWord: 'сварливый'},
    {enWord: 'to scream', rusWord: 'кричать'},
    {enWord: 'screwdriver', rusWord: 'отвертка'},
    {enWord: 'fuse', rusWord: 'предохранитель'},
    {enWord: 'to mend', rusWord: 'исправить'},
    {enWord: 'commitment', rusWord: 'обязательство'},
    {enWord: 'spell out', rusWord: 'сформулировать'},
    {enWord: 'orphan', rusWord: 'сирота'},
    {enWord: 'orphanage', rusWord: 'детский дом'},
    {enWord: 'harebrained', rusWord: 'легкомысленный'},
    {enWord: 'survey', rusWord: 'исследование'},
    {enWord: 'think it over', rusWord: 'обдумать'},
    {enWord: 'to deserve', rusWord: 'заслужить'},
    {enWord: 'slump', rusWord: 'спад'},
    {enWord: 'to wander', rusWord: 'блуждать'},
    {enWord: 'trail', rusWord: 'след'},
    {enWord: 'prairie', rusWord: 'степь'},
    {enWord: 'to keep over', rusWord: 'удерживать'},
    {enWord: 'to ring out', rusWord: 'прозвучать'},
    {enWord: 'valley', rusWord: 'долина'},
    {enWord: 'contraction', rusWord: 'сокращение'},
    {enWord: 'ambien', rusWord: 'снотворное'},
    {enWord: 'awesome', rusWord: 'великолепно'},
    {enWord: 'unresponsive', rusWord: 'без сознания'},
    {enWord: 'affirmative', rusWord: 'позитивный'},
    {enWord: 'malfunction', rusWord: 'неисправность', rusWord2:'поломка'},
    {enWord: 'determination', rusWord: 'определение'},
    {enWord: 'immutable', rusWord: 'неизменный'},
    {enWord: 'immutability', rusWord: 'неизменность'},
    {enWord: 'to terminate', rusWord: 'прервать'},
    {enWord: 'to shatter', rusWord: 'разрушить'},
    {enWord: 'wind', rusWord: 'ветер'},
    {enWord: 'to wind up', rusWord: 'закончить', rusWord2:'занести'},
    {enWord: 'suing', rusWord: 'судиться'},
    {enWord: 'to lash', rusWord: 'хлестать'},
    {enWord: 'lash', rusWord: 'плеть'},
    {enWord: 'to lash out', rusWord: 'наброситься'},
    {enWord: 'closure', rusWord: 'закрытие'},
    {enWord: 'brown-nosing', rusWord: 'подлиза'},
    {enWord: 'scale', rusWord: 'масштаб'},
    {enWord: 'to prosecute', rusWord: 'привлекать к суду'},
    {enWord: 'to parse', rusWord: 'анализировать'},
    {enWord: 'to accuse', rusWord: 'обвинять'},
    {enWord: 'response', rusWord: 'реакция', rusWord2:'ответ'},
    {enWord: 'to show up', rusWord: 'появиться', rusWord2:'явиться', rusWord3:'придти'},
    {enWord: 'pity', rusWord: 'жалость'},
    {enWord: 'bride', rusWord: 'невеста'},
    {enWord: 'to insist', rusWord: 'настаивать', rusWord2:'требовать'},
    {enWord: 'horrendous', rusWord: 'ужасный'},
    {enWord: 'otherwise', rusWord: 'иначе'},

]