import {StateType} from "./MainList";

export let stateOfWords: Array<StateType> = [

    {enWord: 'embodiment', rusWord: 'воплощение', rusWord2:'олицетворение'},
    {enWord: 'accomplish', rusWord: 'добиться', rusWord2:'достичь'},
    {enWord: 'no way', rusWord: 'ни за что', rusWord2:'да ладно'},
    {enWord: 'essential', rusWord: 'необходимо', rusWord2:'важно'},
    {enWord: 'to slam', rusWord: 'хлопнуть', rusWord2:'швырнуть'},
    {enWord: 'somehow', rusWord: 'некторым образом', rusWord2:'так или иначе'},
    {enWord: 'box office', rusWord: 'касса', rusWord2:'кассовые сборы'},
    {enWord: 'assume', rusWord: 'предположить', rusWord2:'взять на себя'},
    {enWord: 'egos', rusWord: 'эго', rusWord2:'самолюбие'},
    {enWord: 'to collaborate', rusWord: 'сотрудничать', rusWord2:'взаимодействовать'},
    {enWord: 'contradiction', rusWord: 'противоречие', rusWord2:'несоответствие'},
    {enWord: 'split up with...', rusWord: 'расстоваться с ...', rusWord2:'разводиться с ...'},
    {enWord: 'interrogation', rusWord: 'допрос', rusWord2:'дознание'},
    {enWord: 'to swarm', rusWord: 'роиться', rusWord2:'толпиться', rusWord3:'заполнять'},
    {enWord: 'expand on a subject', rusWord: 'распространяться на тему', rusWord2:'подробнее на эту тему'},
    {enWord: 'degree', rusWord: 'градус', rusWord2:'диплом', rusWord3:'научная степень'},
    {enWord: 'to consider', rusWord: 'рассмотреть', rusWord2:'учесть', rusWord3:'предусмотреть'},
    {enWord: 'struggle', rusWord: 'борьба', rusWord2:'драка', rusWord3:'битва'},
    {enWord: 'appearance', rusWord: 'появление', rusWord2:'внешний вид', rusWord3:'матч'},
    {enWord: 'hurt', rusWord: 'вред'},
    {enWord: 'to share', rusWord: 'делить'},
    {enWord: 'detached house', rusWord: 'отдельный дом'},
    {enWord: 'residential area', rusWord: 'жилой район'},
    {enWord: 'hot air balloon', rusWord: 'воздушный шар'},
    {enWord: 'for your record', rusWord: 'к твоему сведению'},
    {enWord: 'it doesn`t matter', rusWord: 'без разницы', rusWord2:'не имеет значения'},
    {enWord: 'it`s up to you', rusWord: 'тебе решать'},
    {enWord: 'let`s give it a shot', rusWord: 'давай попробуем'},
    {enWord: 'cinnamon rolls', rusWord: 'булочки с корицей'},
    {enWord: 'give it up', rusWord: 'встречайте', rusWord2:'приветствуйте'},
    {enWord: 'affordable', rusWord: 'доступный', rusWord2:'приемлемый'},
    {enWord: 'sucker punch', rusWord: 'удар из под тишка'},
    {enWord: 'pickle juice', rusWord: 'рассол'},
    {enWord: 'outskirts', rusWord: 'отшиб города'},
    {enWord: 'suburb', rusWord: 'пригород'},
    {enWord: 'rush hour', rusWord: 'час пик'},
    {enWord: 'contemporary', rusWord: 'современный'},
    {enWord: 'picturesque', rusWord: 'живописный'},
    {enWord: 'fascinating', rusWord: 'очаровательный'},
    {enWord: 'inner cities', rusWord: 'центр города'},
    {enWord: 'conveniently located', rusWord: 'удобно расположен'},
    {enWord: 'convinced', rusWord: 'убежденный'},
    {enWord: 'initial', rusWord: 'первоначальный'},
    {enWord: 'vague', rusWord: 'неясный'},
    {enWord: 'overcrowded', rusWord: 'перенаселен'},
    {enWord: 'apartment blocks', rusWord: 'многоквартирный дом'},
    {enWord: 'get mortgages', rusWord: 'взять ипотеку'},
    {enWord: 'to drop somebody off', rusWord: 'высадить кого-либо'},
    {enWord: 'self-catering accommodation', rusWord: 'жилье с самообслуживанием'},
    {enWord: 'to get around the city', rusWord: 'передвигаться по городу'},
    {enWord: 'in the off-season', rusWord: 'вне сезона'},
    {enWord: 'local crafts', rusWord: 'местные сувениры'},
    {enWord: 'on your own', rusWord: 'самостоятельно'},
    {enWord: 'stopover', rusWord: 'остановка'},
    {enWord: 'buzzing', rusWord: 'жжужание'},
    {enWord: 'dumplings', rusWord: 'пельмени'},
    {enWord: 'it`s grossing me out', rusWord: 'это выводит меня из себя'},
    {enWord: 'marshmallow', rusWord: 'зефир'},
    {enWord: 'to put up with', rusWord: 'мириться с чем-то'},
    {enWord: 'to pay off mortgages', rusWord: 'выплатить ипотеку'},
    {enWord: 'to get stuck in a traffic jam', rusWord: 'застрять в пробке'},
    {enWord: 'hectic', rusWord: 'суматошный',rusWord2:'напряженный'},
    {enWord: 'to express', rusWord: 'заявлять',rusWord2:'выражать'},
    {enWord: 'to pick up', rusWord: 'подобрать',rusWord2:'забрать'},
    {enWord: 'reluctant', rusWord: 'нежелание',rusWord2:'не по совей вине'},
    {enWord: 'get off your high horse', rusWord: 'спустись с небес на землю'},
    {enWord: 'chanterelle', rusWord: 'лисички'},
    {enWord: 'I`ll see you around', rusWord: 'увидимся'},
    {enWord: 'What is it to me', rusWord: 'Какое мне до этого дело'},
    {enWord: 'have a lot in common', rusWord: 'много общего'},
    {enWord: 'get on well with somebody', rusWord: 'ладить с кем-либо'},
    {enWord: 'keep in touch with', rusWord: 'поддерживать отношения'},
    {enWord: 'strained relations', rusWord: 'натянутые отношения'},
    {enWord: 'warm relations', rusWord: 'теплые отношения'},
    {enWord: 'family gathering', rusWord: 'семейные встречи'},
    {enWord: 'household chores', rusWord: 'работа по дому'},
    {enWord: 'to charge somebody rent', rusWord: 'брать плату за проживание'},
    {enWord: 'well-behaved', rusWord: 'воспитанный'},
    {enWord: 'I don`t wanna overstay my welcome', rusWord: 'я не хочу злоупотреблять твоим гостепреимством'},
    {enWord: 'Could you be more specific?', rusWord: 'Можно поконкретнее?'},
    {enWord: 'Don`t be mad at me', rusWord: 'Не сердись на меня'},
    {enWord: 'I don`t wanna put you in the middle of it', rusWord: 'я не хочу тебя впутывать в это'},
    {enWord: 'it`s off the table', rusWord: 'это не обсуждается'},
    {enWord: 'rival', rusWord: 'соперник'},
    {enWord: 'bachelor party', rusWord: 'мальчишник'},
    {enWord: 'long-distance relationships', rusWord: 'отношения на расстоянии'},
    {enWord: 'to go out with', rusWord: 'встречаться с', rusWord2:'иметь отношения с'},
    {enWord: 'naughty', rusWord: 'непослушный', rusWord2:'капризный'},
    {enWord: 'competitive', rusWord: 'конкурентный'},
    {enWord: 'have a crush on each other', rusWord: 'влюбиться друг в друга'},
    {enWord: 'to expand', rusWord: 'расширять'},
    {enWord: 'overcoming', rusWord: 'преодоление'},
    {enWord: 'willing', rusWord: 'готовый',rusWord2:'согласный', rusWord3:'желающий'},
    {enWord: 'ladle', rusWord: 'половник'},
    {enWord: 'colander', rusWord: 'дуршлаг'},
    {enWord: 'cutting board', rusWord: 'разделочная доска'},
    {enWord: 'chopping board', rusWord: 'разделочная доска'},
    {enWord: 'can opener', rusWord: 'консервный нож'},
    {enWord: 'corkscrew', rusWord: 'штопор'},
    {enWord: 'spatula', rusWord: 'лопатка',rusWord2:'лопатка для жарки'},
    {enWord: 'to settle', rusWord: 'решить',rusWord2:'урегулировать'},
    {enWord: 'indomitable', rusWord: 'несгибаемый',rusWord2:'неукротимый'},
    {enWord: 'pull it off', rusWord: 'справиться с этим',rusWord2:'получиться'},
    {enWord: 'modest', rusWord: 'скромный'},
    {enWord: 'glint in the eye', rusWord: 'блеск в глазах'},
    {enWord: 'martial arts', rusWord: 'боевые исскуства'},
    {enWord: 'smirk', rusWord: 'ухмылка'},
    {enWord: 'generous', rusWord: 'щедрый'},
    {enWord: 'gamble', rusWord: 'игра',rusWord2:'риск', rusWord3:'азарт'},
    {enWord: 'selfish', rusWord: 'эгоистичный'},
    {enWord: 'get along with somebody', rusWord: 'ладить с кем-либо'},
    {enWord: 'outgoing people', rusWord: 'общительные люди'},
    {enWord: 'open minded', rusWord: 'широких взглядов'},
    {enWord: 'narrow minded', rusWord: 'узких взглядов'},
    {enWord: 'think outside the box', rusWord: 'думать нестандартно'},
    {enWord: 'reserved person', rusWord: 'закрытый человек'},
    {enWord: 'to achieve goals', rusWord: 'достигать цели'},
    {enWord: 'to mess up', rusWord: 'испортить', rusWord2:'завалить'},
    {enWord: 'book', rusWord: 'книга'},
    {enWord: 'treadmill', rusWord: 'беговая дорожка'},
    {enWord: 'tread', rusWord: 'шаг', rusWord2:'протектор'},
    {enWord: 'keep it together', rusWord: 'держи себя в руках', rusWord2:'сохраняй спокойствие'},
    {enWord: 'indifferent', rusWord: 'различный', rusWord2:'равнодушный'},
    {enWord: 'tread lightly', rusWord: 'действовать осторожно'},
    {enWord: 'to be ambitious', rusWord: 'быть амбициозным'},
    {enWord: 'to work hard on something', rusWord: 'усердно работать над чем-либо'},
    {enWord: 'to miss out', rusWord: 'пропустить'},
    {enWord: 'mental', rusWord: 'психический'},
    {enWord: 'to encourage to do something', rusWord: 'воодушевлять что-то сделать'},
    {enWord: 'to occur', rusWord: 'происходить', rusWord2:'иметь место'},
    {enWord: 'mayhem', rusWord: 'хаос', rusWord2:'беспредел'},
    {enWord: 'orbital bone', rusWord: 'скуловая кость'},
    {enWord: 'to master different skills', rusWord: 'получать разные навыки'},
    {enWord: 'to focus on something', rusWord: 'сосредоточиться на чем-то',rusWord2:'сконцентрироваться на чем-то'},
    {enWord: 'to beg', rusWord: 'умолять'},
    {enWord: 'corpse', rusWord: 'мертвец'},
    {enWord: 'mortician', rusWord: 'гробовщик'},
    {enWord: 'den', rusWord: 'логово'},
    {enWord: 'thirsty', rusWord: 'жажда'},
    {enWord: 'amusement', rusWord: 'развлечение'},
    {enWord: 'thoughtful', rusWord: 'заботливый'},
    {enWord: 'grumpy', rusWord: 'сварливый'},
    {enWord: 'to scream', rusWord: 'кричать'},
    {enWord: 'screwdriver', rusWord: 'отвертка'},
    {enWord: 'fuse', rusWord: 'предохранитель'},
    {enWord: 'to mend', rusWord: 'исправить'},
    {enWord: 'commitment', rusWord: 'обязательство'},
    {enWord: 'spell out', rusWord: 'сформулировать'},
    {enWord: 'orphan', rusWord: 'сирота'},
    {enWord: 'orphanage', rusWord: 'детский дом'},
    {enWord: 'harebrained', rusWord: 'легкомысленный'},
    {enWord: 'survey', rusWord: 'исследование'},
    {enWord: 'think it over', rusWord: 'обдумать'},
    {enWord: 'to deserve', rusWord: 'заслужить'},
    {enWord: 'slump', rusWord: 'спад'},
    {enWord: 'to wander', rusWord: 'блуждать'},
    {enWord: 'trail', rusWord: 'след'},
    {enWord: 'prairie', rusWord: 'степь'},
    {enWord: 'to keep over', rusWord: 'удерживать'},
    {enWord: 'to ring out', rusWord: 'прозвучать'},
    {enWord: 'valley', rusWord: 'долина'},
    {enWord: 'contraction', rusWord: 'сокращение'},
    {enWord: 'ambien', rusWord: 'снотворное'},
    {enWord: 'awesome', rusWord: 'великолепно'},
    {enWord: 'unresponsive', rusWord: 'без сознания'},
    {enWord: 'affirmative', rusWord: 'позитивный'},
    {enWord: 'malfunction', rusWord: 'неисправность', rusWord2:'поломка'},
    {enWord: 'determination', rusWord: 'определение'},
    {enWord: 'immutable', rusWord: 'неизменный'},
    {enWord: 'immutability', rusWord: 'неизменность'},
    {enWord: 'to terminate', rusWord: 'прервать'},
    {enWord: 'to shatter', rusWord: 'разрушить'},
    {enWord: 'wind', rusWord: 'ветер'},
    {enWord: 'to wind up', rusWord: 'закончить', rusWord2:'занести'},
    {enWord: 'suing', rusWord: 'судиться'},
    {enWord: 'to lash', rusWord: 'хлестать'},
    {enWord: 'lash', rusWord: 'плеть'},
    {enWord: 'to lash out', rusWord: 'наброситься'},
    {enWord: 'closure', rusWord: 'закрытие'},
    {enWord: 'brown-nosing', rusWord: 'подлиза'},
    {enWord: 'scale', rusWord: 'масштаб'},
    {enWord: 'to prosecute', rusWord: 'привлекать к суду'},
    {enWord: 'to parse', rusWord: 'анализировать'},
    {enWord: 'to accuse', rusWord: 'обвинять'},
    {enWord: 'response', rusWord: 'реакция', rusWord2:'ответ'},
    {enWord: 'to show up', rusWord: 'появиться', rusWord2:'явиться', rusWord3:'придти'},
    {enWord: 'pity', rusWord: 'жалость'},
    {enWord: 'bride', rusWord: 'невеста'},
    {enWord: 'to insist', rusWord: 'настаивать', rusWord2:'требовать'},
    {enWord: 'horrendous', rusWord: 'ужасный'},
    {enWord: 'otherwise', rusWord: 'иначе'},
    {enWord: 'curse', rusWord: 'проклятие'},
    {enWord: 'first-grader', rusWord: 'первоклассник'},
    {enWord: 'fictional', rusWord: 'вымышленный'},
    {enWord: 'ransom', rusWord: 'выкуп'},
    {enWord: 'disguise', rusWord: 'маскировка'},
    {enWord: 'make out', rusWord: 'целоваться'},
    {enWord: 'to get away from it all', rusWord: 'сбежать от всего этого'},
    {enWord: 'to set off', rusWord: 'отправиться в путь'},
    {enWord: 'to see somebody off', rusWord: 'проводить кого-либо'},
    {enWord: 'to get on a plane', rusWord: 'сесть в самолет'},
    {enWord: 'to get off the plane', rusWord: 'выйти из самолета'},
    {enWord: 'slightly less', rusWord: 'немного меньше'},
    {enWord: 'What is so funny about that?', rusWord: 'Что в этом смешного?'},
    {enWord: 'The bottom line is that...', rusWord: 'Суть в том...'},
    {enWord: 'entire', rusWord: 'целый'},
    {enWord: 'courageous', rusWord: 'мужественно'},
    {enWord: 'feud', rusWord: 'вражда'},
    {enWord: 'say in private', rusWord: 'сказать наедине'},
    {enWord: 'screw around', rusWord: 'валять дурака'},
    {enWord: 'legislator', rusWord: 'законодатель'},
    {enWord: 'recently', rusWord: 'недавно'},
    {enWord: 'recent', rusWord: 'последний'},
    {enWord: 'to attend', rusWord: 'посещать',rusWord2:'присутствовать' },
    {enWord: 'to expect', rusWord: 'ожидать'},
    {enWord: 'nothing less', rusWord: 'ничего другого'},
    {enWord: 'straightforward', rusWord: 'прямолинейный'},
    {enWord: 'to set deadlines', rusWord: 'установить срок'},
    {enWord: 'to meet deadlines', rusWord: 'уложиться в срок'},
    {enWord: 'to slack off', rusWord: 'расслабиться'},
    {enWord: 'high powered jobs', rusWord: 'высокая должность'},
    {enWord: 'to work in shifts', rusWord: 'работать посменно'},
    {enWord: 'it`s not a big deal', rusWord: 'ничего особенного'},
    {enWord: 'how come?', rusWord: 'Как так вышло?'},
    {enWord: 'to have a burnout', rusWord: 'перегореть'},
    {enWord: 'benefits package', rusWord: 'социальный пакет'},
    {enWord: 'sick leave', rusWord: 'больничный'},
    {enWord: 'maternity leave', rusWord: 'декретный отпуск'},
    {enWord: 'to get stuck behind a desk', rusWord: 'застрять за работой'},
    {enWord: 'I`m fed up', rusWord: 'Я сыт по горло'},
    {enWord: 'get down to', rusWord: 'приступить'},
    {enWord: 'to binge', rusWord: 'напиться', rusWord2:'пьянствовать'},
    {enWord: 'flow state', rusWord: 'состояние потока'},
    {enWord: 'pinkie', rusWord: 'мизинец'},
    {enWord: 'rod', rusWord: 'стержень'},
    {enWord: 'clutch', rusWord: 'тиски'},
    {enWord: 'to clutch', rusWord: 'схватить'},
    {enWord: 'to mutter', rusWord: 'бормотать'},
    {enWord: 'dagger', rusWord: 'кинжал'},
    {enWord: 'trapdoor', rusWord: 'люк'},
    {enWord: 'drizzle', rusWord: 'морось'},
    {enWord: 'rather', rusWord: 'лучше', rusWord2:'довольно'},
    {enWord: 'it`s rather cold', rusWord: 'довольно холодно'},
    {enWord: 'to exclaim', rusWord: 'воскликнуть'},
    {enWord: 'to rub', rusWord: 'тереть'},
    {enWord: 'splendid', rusWord: 'великолепный'},
    {enWord: 'villain', rusWord: 'злодей'},
    {enWord: 'elbow', rusWord: 'локоть'},
    {enWord: 'arsenic', rusWord: 'мышьяк'},
    {enWord: 'to knock', rusWord: 'стучать'},
    {enWord: 'to knock out', rusWord: 'выбить'},
    {enWord: 'ensemble', rusWord: 'ансамбль'},
    {enWord: 'chill', rusWord: 'прохладный'},
    {enWord: 'cave', rusWord: 'пещера'},
    {enWord: 'simmering', rusWord: 'кипение'},
    {enWord: 'toad', rusWord: 'жаба'},
    {enWord: 'he stung with remorse', rusWord: 'Он терзался угрызениями совести'},
    {enWord: 'remorse', rusWord: 'раскаяние',rusWord2:'угрызения совести'},
    {enWord: 'to figure out', rusWord: 'выяснять',rusWord2:'вычислять'},
    {enWord: 'to defy', rusWord: 'игнорировать',rusWord2:'бросать вызов'},
    {enWord: 'smoothly', rusWord: 'гладко',rusWord2:'плавно'},
    {enWord: 'witch', rusWord: 'ведьма',rusWord2:'колдунья'},
    {enWord: 'kettle', rusWord: 'чайник',rusWord2:'котел'},
    {enWord: 'put off', rusWord: 'откладывать',rusWord2:'отвлекать'},
    {enWord: 'it`s drizzling', rusWord: 'моросит'},
    {enWord: 'incantation', rusWord: 'заклинание'},
    {enWord: 'chain', rusWord: 'цепь'},
    {enWord: 'manfully', rusWord: 'мужественно'},
    {enWord: 'cough', rusWord: 'кашель'},
    {enWord: 'cough it up', rusWord: 'кашляйте'},
    {enWord: 'purpose', rusWord: 'цель'},
    {enWord: 'freak', rusWord: 'ненормальный'},
    {enWord: 'to appreciate', rusWord: 'ценить'},
    {enWord: 'legit', rusWord: 'законный'},
    {enWord: 'fellas', rusWord: 'ребята'},
    {enWord: 'dude', rusWord: 'чувак'},
    {enWord: 'nerve-wracking', rusWord: 'нервотрепка'},
    {enWord: 'shape', rusWord: 'форма'},
    {enWord: 'bonker', rusWord: 'помешательство'},
    {enWord: 'he is bonkers', rusWord: 'он чокнутый'},
    {enWord: 'freak out', rusWord: 'психовать'},
    {enWord: 'footage', rusWord: 'отснятый материал'},
    {enWord: 'to accuse', rusWord: 'обвинять'},
    {enWord: 'to bind', rusWord: 'связывать'},
    {enWord: 'to squeeze', rusWord: 'сжимать'},
    {enWord: 'to squirm', rusWord: 'ерзать'},
    {enWord: 'to set back', rusWord: 'препятствовать'},
    {enWord: 'to flatter', rusWord: 'льстить'},
    {enWord: 'to empower', rusWord: 'уполномачивать'},
    {enWord: 'to regard', rusWord: 'считаться'},
    {enWord: 'to crawl', rusWord: 'ползать'},
    {enWord: 'to offend', rusWord: 'обидеть'},
    {enWord: 'to crawl on knees', rusWord: 'ползти на коленях'},
    {enWord: 'it boils down to', rusWord: 'сводится к'},
    {enWord: 'to boil', rusWord: 'варить'},
    {enWord: 'to collide', rusWord: 'сталкиваться'},
    {enWord: 'to blow', rusWord: 'дуть'},
    {enWord: 'to remain', rusWord: 'оставаться'},
    {enWord: 'blow', rusWord: 'прорыв'},
    {enWord: 'outcast', rusWord: 'изгой'},
    {enWord: 'concrete', rusWord: 'бетон'},
    {enWord: 'betrayer', rusWord: 'предатель'},
    {enWord: 'tomb', rusWord: 'могила'},
    {enWord: 'to shed', rusWord: 'пролить'},
    {enWord: 'to abide', rusWord: 'оставаться'},
    {enWord: 'blade', rusWord: 'клинок'},
    {enWord: 'apart from that', rusWord: 'в отличие от этого'},
    {enWord: 'tide', rusWord: 'волна'},
    {enWord: 'sinister', rusWord: 'зловещий'},
    {enWord: 'to go out with', rusWord: 'идти на свидание'},
    {enWord: 'tub', rusWord: 'ванна'},
    {enWord: 'none of the above', rusWord: 'ничего из вышеперечисленного'},
    {enWord: 'other then you', rusWord: 'кроме тебя'},
    {enWord: 'reprimand', rusWord: 'замечание'},
    {enWord: 'to reprimand', rusWord: 'сделать замечание'},
    {enWord: 'bastard', rusWord: 'ублюдок'},
    {enWord: 'no one would have ever noticed', rusWord: 'никто бы никогда и не заметил'},
    {enWord: 'move', rusWord: 'движение', rusWord2:'поступок'},
    {enWord: 'to allude', rusWord: 'ссылаться', rusWord2:'намекать'},
    {enWord: 'hilarious', rusWord: 'уморительный', rusWord2:'веселый'},
    {enWord: 'baubles', rusWord: 'побрякушки', rusWord2:'украшения'},
    {enWord: 'alien', rusWord: 'чужой', rusWord2:'инопланетянин'},
    {enWord: 'face him again', rusWord: 'встретиться с ним опять'},
    {enWord: 'trade', rusWord: 'торговля', rusWord2:'ремесло'},
    {enWord: 'profusely', rusWord: 'обильно', rusWord2:'чрезмерно'},
    {enWord: 'to complain profusely', rusWord: 'жаловаться сильно'},
    {enWord: 'confession', rusWord: 'признание'},
    {enWord: 'decisive', rusWord: 'решительный'},
    {enWord: 'decisiveness', rusWord: 'решительность'},
    {enWord: 'sudden', rusWord: 'внезапный'},
    {enWord: 'insane', rusWord: 'сумасшедший'},
    {enWord: 'there is something we gotta to do', rusWord: 'что-то собираемся сделать'},
    {enWord: 'I am very flattered', rusWord: 'Я польщен'},
    {enWord: 'definitely', rusWord: 'определенно'},
    {enWord: 'I know of some cases', rusWord: 'Я знаю пару члучаев'},
    {enWord: 'not anymore', rusWord: 'уже нет'},
    {enWord: 'buck up', rusWord: 'встряхнуться'},
    {enWord: 'impersonate', rusWord: 'исполнять роль'},
    {enWord: 'discretion', rusWord: 'усмотрение',rusWord2:'благоразумие', rusWord3:'осторожность'},
    {enWord: 'indiscretion', rusWord: 'неусмотрительность',rusWord2:'неблагоразумие', rusWord3:'неосторожность'},
    {enWord: 'I was asking around about you', rusWord: 'я распрашивал о тебе повсюду'},
    {enWord: 'gosh', rusWord: 'черт возьми'},
    {enWord: 'rural', rusWord: 'деревенский'},
    {enWord: 'sprawling', rusWord: 'раскидистый'},
    {enWord: 'mob', rusWord: 'толпа'},
    {enWord: 'sword', rusWord: 'меч'},
    {enWord: 'maid', rusWord: 'горничная'},
    {enWord: 'pistol', rusWord: 'пистолет'},
    {enWord: 'accurate', rusWord: 'точный'},
    {enWord: 'rig', rusWord: 'буровая установка'},
    {enWord: 'goatee', rusWord: 'козлиная бородка'},
    {enWord: 'pal', rusWord: 'приятель'},
    {enWord: 'blind', rusWord: 'слепой'},
    {enWord: 'fierce', rusWord: 'свирепый'},
    {enWord: 'here is thing', rusWord: 'вот в чем дело'},
    {enWord: 'messiah', rusWord: 'мессия'},
    {enWord: 'blame', rusWord: 'вина'},
    {enWord: 'viral', rusWord: 'вирус'},
    {enWord: 'sober', rusWord: 'трезвый'},
    {enWord: 'release', rusWord: 'освобождение'},
    {enWord: 'renegade', rusWord: 'отступник', rusWord2:'изменник'},
    {enWord: 'favors', rusWord: 'благосклонность'},
    {enWord: 'grain', rusWord: 'зерно'},
    {enWord: 'scout', rusWord: 'разведчик'},
    {enWord: 'apparently', rusWord: 'по всей видимости'},
    {enWord: 'prejudice', rusWord: 'предрассудки'},
    {enWord: 'hear me out', rusWord: 'выслушай меня'},
    {enWord: 'gratitude', rusWord: 'благодарность'},
    {enWord: 'I am grateful to you', rusWord: 'Я признателен тебе'},
    {enWord: 'to plug', rusWord: 'затыкать'},
    {enWord: 'lad', rusWord: 'парень'},
    {enWord: 'to sober up', rusWord: 'протрезветь'},
    {enWord: 'to pray', rusWord: 'молиться'},
    {enWord: 'wound', rusWord: 'рана'},
    {enWord: 'enemy', rusWord: 'враг'},
    {enWord: 'scar', rusWord: 'шрам'},
    {enWord: 'juniper', rusWord: 'можжевельник'},
    {enWord: 'to stretch', rusWord: 'растянуть'},
    {enWord: 'unconditionally', rusWord: 'безусловно'},
    {enWord: 'dreadful', rusWord: 'страшный',rusWord2:'ужасный'},
    {enWord: 'to complain', rusWord: 'жаловаться'},
    {enWord: 'to carry on', rusWord: 'продолжить'},
    {enWord: 'to make sure', rusWord: 'убеждаться'},
    {enWord: 'to be capable of', rusWord: 'быть в состоянии'},
    {enWord: 'to learn from ...', rusWord: 'учиться у...'},
    {enWord: 'to say out loud', rusWord: 'говорить вслух'},
    {enWord: 'to fall into...', rusWord: 'впасть в ...'},
    {enWord: 'to speak ill of somebody', rusWord: 'говорить плохо о ком-то'},
    {enWord: 'prophet', rusWord: 'пророк'},
    {enWord: 'gossip', rusWord: 'сплетни'},
    {enWord: 'to deceive', rusWord: 'обманывать'},
    {enWord: 'to prove', rusWord: 'доказывать'},
    {enWord: 'to climb', rusWord: 'взбираться'},
    {enWord: 'we are the only one`s here', rusWord: 'мы здесь только одни'},
    {enWord: 'it`s a first ball in the avalanche', rusWord: 'это первый снежок в лавине'},
    {enWord: 'there is no place like home', rusWord: 'в гостях хорошо, а дома лучше'},
    {enWord: 'buddy', rusWord: 'приятель'},
    {enWord: 'seek', rusWord: 'искать'},
    {enWord: 'welfare', rusWord: 'благосостояние'},
    {enWord: 'rumor', rusWord: 'слух, молва'},
    {enWord: 'stronghold', rusWord: 'оплот',rusWord2:'цитадель'},
    {enWord: 'dotted', rusWord: 'пунктирный'},
    {enWord: 'solid', rusWord: 'твердый', rusWord2:'сплошной'},
    {enWord: 'rough', rusWord: 'грубый'},
    {enWord: 'wickiup', rusWord: 'хижина'},
    {enWord: 'tongue', rusWord: 'язык'},
    {enWord: 'holiest', rusWord: 'святейший'},
    {enWord: 'to spit on', rusWord: 'наплевать'},
    {enWord: 'to hesitate', rusWord: 'стесняться'},
    {enWord: 'apparently', rusWord: 'судя по всему'},
    {enWord: 'gutter', rusWord: 'водосточный желоб'},
    {enWord: 'in the gutter', rusWord: 'в полной разрухе'},
    {enWord: 'truth be told', rusWord: 'по правде говоря'},
    {enWord: 'graduate', rusWord: 'выпускаться из колледжа'},
    {enWord: 'no big deal', rusWord: 'ничего особенного'},
    {enWord: 'drop out', rusWord: 'отчислиться'},
    {enWord: 'unwed', rusWord: 'незамужняя'},
    {enWord: 'adopt', rusWord: 'усыновлять'},
    {enWord: 'to relent', rusWord: 'смягчаться'},
    {enWord: 'tuition', rusWord: 'образование'},
    {enWord: 'to stumble', rusWord: 'спотыкаться'},
    {enWord: 'to stumble into', rusWord: 'наткнуться'},
    {enWord: 'I can`t to keep up with', rusWord: 'не могу не отставать'},
    {enWord: 'to find out', rusWord: 'выяснить'},
    {enWord: 'to drop off', rusWord: 'бросать'},
    {enWord: 'wilderness', rusWord: 'дикость'},
    {enWord: 'in a middle of nowhere', rusWord: 'черт знает где'},
    {enWord: 'enthralled', rusWord: 'увлеченный'},
    {enWord: 'commencement', rusWord: 'начало',rusWord2:'возбуждение (дела)',rusWord3:'вручение дипломов'},
    {enWord: 'sweat', rusWord: 'пот'},
    {enWord: 'we sweat a lot', rusWord: 'мы много потеем'},
    {enWord: 'I am honored to be with you', rusWord: 'мне выпала честь быть с вами'},
    {enWord: 'to hire', rusWord: 'нанимать'},
    {enWord: 'local', rusWord: 'местный'},
    {enWord: 'take it all off', rusWord: 'снимай это все'},
    {enWord: 'if you think about it', rusWord: 'если задуматься'},
    {enWord: 'inappropriate', rusWord: 'неуместный'},
    {enWord: 'classy joint', rusWord: 'классное заведение'},
    {enWord: 'tight', rusWord: 'тесный'},
    {enWord: 'to excite', rusWord: 'взволнован'},
    {enWord: 'to admit', rusWord: 'признать'},
    {enWord: 'to try on', rusWord: 'примерять'},
    {enWord: 'to intend', rusWord: 'намереваться'},
    {enWord: 'to intention', rusWord: 'намерение'},
    {enWord: 'irresponsible', rusWord: 'безответственность'},
    {enWord: 'to check out', rusWord: 'заценить'},
    {enWord: 'high brow', rusWord: 'высокоинтеллектуальный'},
    {enWord: 'to rehearse', rusWord: 'репетировать'},
    {enWord: 'in rehearsal', rusWord: 'в ходе репетиции'},
    {enWord: 'to be on great terms with...', rusWord: 'быть в хороших отношениях с...'},
    {enWord: 'piano strings', rusWord: 'струны пианино'},
    {enWord: 'pitchy', rusWord: 'фальшивый'},
    {enWord: 'lift it up', rusWord: 'поднять'},
    {enWord: 'turn him loose', rusWord: 'отпусти его'},
    {enWord: 'pull up stakes', rusWord: 'смотать удочки, сняться с места'},
    {enWord: 'come on over', rusWord: 'давай же'},
    {enWord: 'no matter what happens', rusWord: 'чтобы не случилось'},
    {enWord: 'to sort the problem out', rusWord: 'решить проблему'},
    {enWord: 'I can not take this any longer', rusWord: 'Я не могу больше это терпеть'},
    {enWord: 'to trick', rusWord: 'хитрить'},
    {enWord: 'equal', rusWord: 'равный'},
    {enWord: 'peanuts', rusWord: 'арахис'},
    {enWord: 'I am living on peanuts', rusWord: 'Я живу за копейки'},
    {enWord: 'stretch my salary', rusWord: 'растянуть зарплату'},
    {enWord: 'tracker', rusWord: 'жучок', rusWord2:'датчик'},
    {enWord: 'challenge', rusWord: 'вызов', rusWord2:'испытание'},
    {enWord: 'timeframe', rusWord: 'период', rusWord2:'срок'},
    {enWord: 'keeping track', rusWord: 'отслеживание'},
    {enWord: 'bitter', rusWord: 'горький'},
    {enWord: 'overwhelmed', rusWord: 'перегружен'},
    {enWord: 'receipt', rusWord: 'чек'},
    {enWord: 'reputable', rusWord: 'авторитетный'},
    {enWord: 'to have a savings for the rainy day', rusWord: 'сбережения на черный день'},
    {enWord: 'overspend', rusWord: 'перерасход'},
    {enWord: 'practice makes perfect', rusWord: 'повторение мать учения'},
    {enWord: 'to invest in property', rusWord: 'инвестировать в недвижимость'},
    {enWord: 'the company went bankrupt', rusWord: 'компания обанкротилась'},
    {enWord: 'actions speak louder than words', rusWord: 'дела говорят сами за себя'},
    {enWord: 'magistracy', rusWord: 'магистратура'},
    {enWord: 'keep out', rusWord: 'держаться в стороне'},
    {enWord: 'keep out of dept', rusWord: 'не лезть в долги'},
    {enWord: 'cover letter', rusWord: 'сопроводительное письмо'},
    {enWord: 'acceptance letter', rusWord: 'письмо-подтверждение'},
    {enWord: 'rejection letter', rusWord: 'письмо-отказ'},
    {enWord: 'sour', rusWord: 'отвратительный'},
    {enWord: 'you have only yourself to blame', rusWord: 'сам виноват'},
    {enWord: 'I am not an expert but...', rusWord: 'я не специалист, но...'},
    {enWord: 'It`s likely that...', rusWord: 'скорее всего...'},
    {enWord: 'fingers crossed', rusWord: 'будем надеятся'},
    {enWord: 'uncooked', rusWord: 'сырой'},
    {enWord: 'end up', rusWord: 'в конечном итоге'},
    {enWord: 'in cursive script', rusWord: 'прописными буквами'},
    {enWord: 'delicious', rusWord: 'очень вкусный'},
    {enWord: 'stunning', rusWord: 'ошеломляющий'},
    {enWord: 'sabbatical', rusWord: 'творческий отпуск'},
    {enWord: 'disgusting', rusWord: 'кислый'},
    {enWord: 'juggling', rusWord: 'жонглирование'},
    {enWord: 'to abduct', rusWord: 'похитить'},
    {enWord: 'keep me posted', rusWord: 'держите меня в курсе'},
    {enWord: 'without equal', rusWord: 'нет равных'},
    {enWord: 'straight away', rusWord: 'сразу', rusWord2:'прямо сейчас'},
    {enWord: 'intentions', rusWord: 'намерения'},
    {enWord: 'I love going out into the sticks', rusWord: 'я люблю бывать в глуши'},
    {enWord: 'gorgeous', rusWord: 'безумной красивая'},
    {enWord: 'asunder', rusWord: 'разделить (пополам, на куски)'},
    {enWord: 'get out of your way', rusWord: 'не буду мешать уйти с пути'},
    {enWord: 'There is a lot to that', rusWord: 'В этом большое значение'},
    {enWord: 'to work under pressure', rusWord: 'работать под давлением'},
    {enWord: 'template designer (imposer)', rusWord: 'верстальщик'},
    {enWord: 'ready-made layout', rusWord: 'готовая верстка'},
    {enWord: 'inheritance', rusWord: 'наследование'},
    {enWord: 'I wish I knew', rusWord: 'хотел бы я знать'},
    {enWord: 'It doesn`t make sense', rusWord: 'это не имеет смысла'},
    {enWord: 'It doesn`t prove a thing', rusWord: 'это ничего не доказывает'},
    {enWord: 'It`s all the same to me', rusWord: 'Мне без разницы'},
    {enWord: 'It`s beside the point', rusWord: 'Это не относится к вопросу'},
    {enWord: 'It`s out of place', rusWord: 'Это не уместно'},
    {enWord: 'Negotiation', rusWord: 'Переговоры'},
    {enWord: 'frustrating', rusWord: 'неприятно'},
    {enWord: 'inconsiderate', rusWord: 'необдуманный'},
    {enWord: 'due to', rusWord: 'благодоря'},
    {enWord: 'interpreneur', rusWord: 'предприниматель'},
    {enWord: 'put together', rusWord: 'собрать вместе'},
    {enWord: 'at someone expense', rusWord: 'за чей-то счет'},
    {enWord: 'layout', rusWord: 'верстка'},
    {enWord: 'a large scale application', rusWord: 'большое приложение'},
    {enWord: 'I am pretty sure that', rusWord: 'Я вполне уверен, что'},
    {enWord: 'I am eager to learn', rusWord: 'Я жадный до учебы'},
    {enWord: 'to be on the same page', rusWord: 'быть на одной волне'},
    {enWord: 'to build rapport with people', rusWord: 'выстроить взаимоотношения'},
    {enWord: 'boilerplate', rusWord: 'шаблон'},
    {enWord: 'humble', rusWord: 'скромный'},
    {enWord: 'to humble', rusWord: 'унизить'},
    {enWord: 'to familiarize', rusWord: 'познакомиться'},
    {enWord: 'acquainted', rusWord: 'знакомы'},
    {enWord: 'deal with issues', rusWord: 'иметь дело с задачами'},
    {enWord: 'work remotely', rusWord: 'работать удаленно'},
    {enWord: 'sedentary work', rusWord: 'сидячая работа'},
    {enWord: 'mundane tasks', rusWord: 'примитивные задачи'},
    {enWord: 'drawback', rusWord: 'недостаток'},
    {enWord: 'stay up late', rusWord: 'сидеть до поздна'},
    {enWord: 'have a nap', rusWord: 'вздремнуть'},
    {enWord: 'synopsis', rusWord: 'краткий обзор'},
    {enWord: 'multi-faceted', rusWord: 'многогранный'},
    {enWord: 'it will take a while', rusWord: 'потребуется время'},
    {enWord: 'I have a lot on my plate', rusWord: 'на меня много навалилось'},
    {enWord: 'to perceive', rusWord: 'воспринимать'},
    {enWord: 'to keep up', rusWord: 'продолжать', rusWord2:'поддерживать', rusWord3:'не отставать'},
    {enWord: 'I can free up some of my time', rusWord: 'Я могу освободить часть своего времени'},
    {enWord: 'Come undone', rusWord: 'зайти в тупик'},
    {enWord: 'forth', rusWord: 'вперед'},
    {enWord: 'parentheses', rusWord: '( )'},
    {enWord: 'angle brackets', rusWord: '< >'},
    {enWord: 'curly braces', rusWord: '{ }'},
    {enWord: 'square braces', rusWord: '[ ]'},
    {enWord: 'single quotes', rusWord: " ' ' "},
    {enWord: 'double quotes', rusWord: ' " " '},
    {enWord: 'bracktick', rusWord: ' ` ` '},
    {enWord: 'astericks', rusWord: ' * '},
    {enWord: 'slash', rusWord: ' / '},
    {enWord: 'backslash', rusWord: ' \ '},
    {enWord: 'pipe', rusWord: ' | '},
    {enWord: 'underscore', rusWord: ' _ '},
    {enWord: 'dash', rusWord: ' - '},
    {enWord: 'to arrange', rusWord: 'организовать'},
    {enWord: 'we take turns cooking', rusWord: 'мы готовим по очереди'},
    {enWord: 'enhance', rusWord: 'усилить'},
    {enWord: 'trait', rusWord: 'черта'},
    {enWord: 'as far as I know', rusWord: 'насколько я знаю'},
    {enWord: 'as far as I understand', rusWord: 'насколько я понимаю'},
    {enWord: 'as far as I remember', rusWord: 'насколько я помню'},
    {enWord: 'bald', rusWord: 'лысый'},
    {enWord: 'even-keeled', rusWord: 'уравновешенный'},
    {enWord: 'Is that familiar to anybody?', rusWord: 'Это знакомо кому-нибудь?'},
    {enWord: 'My watches is slow', rusWord: 'мои часы отстают'},
    {enWord: 'Do you know what I am talking about?', rusWord: 'Знаешт о чем я говорю?'},
    {enWord: 'significantly', rusWord: 'значительно'},
    {enWord: 'frankly speaking', rusWord: 'откровенно говоря'},
    {enWord: 'noticeable', rusWord: 'заметный'},
    {enWord: 'instead of', rusWord: 'вместо'},
    {enWord: 'back to square one', rusWord: 'вернуться к началу'},
    {enWord: 'get up to speed', rusWord: 'входить в курс дела'},
    {enWord: 'up to now', rusWord: 'до настоящего момента'},
    {enWord: 'if I have this right', rusWord: 'если я прав'},
    {enWord: 'sophomore', rusWord: 'второкурсник'},
    {enWord: 'crew', rusWord: 'экипаж'},
    {enWord: 'concern', rusWord: 'беспокойство'},
    {enWord: 'eye-opening', rusWord: 'поучительный'},
    {enWord: 'spine-tingling', rusWord: 'мурашки по спине'},
    {enWord: 'heavy going', rusWord: 'медленный прогресс'},
    {enWord: 'page turner', rusWord: 'занятное чтиво'},
    {enWord: 'criteria', rusWord: 'критерии'},
    {enWord: 'gripping', rusWord: 'захватывающий'},
    {enWord: 'riveting', rusWord: 'захватывающий'},
    {enWord: 'prediction', rusWord: 'прогноз'},
    {enWord: 'artificial intelligence', rusWord: 'исскуственный интеллект'},
    {enWord: 'initiative', rusWord: 'инициатива'},
    {enWord: 'self-esteem', rusWord: 'самооценка'},
    {enWord: 'to relieve stress', rusWord: 'снять стресс'},
    {enWord: 'unraveling of the plot', rusWord: 'распутывание сюжета'},
    {enWord: 'refresh your mind', rusWord: 'освежить мысли'},
    {enWord: 'it helps to express yourself', rusWord: 'это помогает выразить себя'},
    {enWord: 'it helps to feel healthy', rusWord: 'это помогает чувствовать себя здоровым'},
    {enWord: 'it helps to avoid depression', rusWord: 'это помогает избежать депрессии'},
    {enWord: 'it makes you well-rounded', rusWord: 'это делает вас разностронним'},
    {enWord: 'augmented reality', rusWord: 'дополненная реальность'},
    {enWord: 'attentive to detail', rusWord: 'внимателен к деталям'},
    {enWord: 'Let`s clear it up', rusWord: 'Давай разберемся'},
    {enWord: 'Let`s drop the subject', rusWord: 'Давай оставим эту тему'},
    {enWord: 'get-go', rusWord: 'с самого начала'},
    {enWord: 'rudimentary code', rusWord: 'простейший код'},
    {enWord: 'to stay on the same page', rusWord: 'быть на одной волне'},
    {enWord: 'to negotiate', rusWord: 'договориться'},
    {enWord: 'to see eye to eye', rusWord: 'найти общий язык'},
    {enWord: 'evolve', rusWord: 'прокачаться'},
    {enWord: 'skillset', rusWord: 'набор навыков'},
    {enWord: 'to speak up for', rusWord: 'выступать за'},
    {enWord: 'to distribute', rusWord: 'распределять'},
    {enWord: 'learning tool', rusWord: 'средства обучения'},
    {enWord: 'to make a point', rusWord: 'делать вывод'},
    {enWord: 'undeserved criticism', rusWord: 'незаслуженная критика'},
    {enWord: 'to fumble', rusWord: 'возиться'},
    {enWord: 'to cause trouble', rusWord: 'доставлять неприятности'},
    {enWord: 'to get rid of', rusWord: 'избавиться от'},
    {enWord: 'retrievable', rusWord: 'восстановимый'},
    {enWord: 'crux of the problem', rusWord: 'суть проблемы'},
    {enWord: 'excuse', rusWord: 'оправдание'},
    {enWord: 'to evaluate', rusWord: 'оценить'},
    {enWord: 'to perform', rusWord: 'выполнить'},
    {enWord: 'to eliminate', rusWord: 'ликвидировать'},
    {enWord: 'to attach to', rusWord: 'прикреплять'},
    {enWord: 'this file was attached to the letter', rusWord: 'этот файл был прикреплен к письму'},
    {enWord: 'the situation could be worse now', rusWord: 'ситуация могла бы быть хуже сейчас'},
    {enWord: 'to suffer from', rusWord: 'страдать от'},
    {enWord: 'what does he suffer from', rusWord: 'от чего он страдает'},
    {enWord: 'to nod', rusWord: 'кивнуть'},
    {enWord: 'He nodded approvingly', rusWord: 'он кивнул одобрительно'},
    {enWord: 'to sink (sank sunk)', rusWord: 'утонуть (о предметах)'},
    {enWord: 'to drown', rusWord: 'утонуть (о людях)'},
    {enWord: 'unexpectedly', rusWord: 'неожиданно'},
    {enWord: 'to devote', rusWord: 'посвещать'},
    {enWord: 'to predict', rusWord: 'предсказать'},
    {enWord: 'coincidence', rusWord: 'стечение обстоятельств'},
    {enWord: 'overconfidence', rusWord: 'чрезмерная уверенность'},
    {enWord: 'suspicious', rusWord: 'подозрительный'},
    {enWord: 'chapter', rusWord: 'глава'},
    {enWord: 'to sweep', rusWord: 'подметать'},
    {enWord: 'as they say, tastes differ', rusWord: 'говорят о вкусах не спорят'},
    {enWord: 'weigh up', rusWord: 'взвесить'},
    {enWord: 'worrisome', rusWord: 'тревожный'},
    {enWord: 'to conduct', rusWord: 'проводить (например эксперимент)'},
    {enWord: 'glass case', rusWord: 'витрина'},
    {enWord: 'price tag', rusWord: 'ценник'},
    {enWord: 'cashdesk', rusWord: 'касса (в магазине)'},
    {enWord: 'thrift shop', rusWord: 'комиссионный магазин'},
    {enWord: 'I am all ears', rusWord: 'слушаю внимательно'},
    {enWord: 'It goes without saying', rusWord: 'само собой разумеется'},
    {enWord: 'It only seems so', rusWord: 'это только так кажется'},
    {enWord: 'It`s touched me to the core', rusWord: 'тронуло до глубины души'},
    {enWord: 'perceive', rusWord: 'воспринимать'},
    {enWord: 'dispiriting', rusWord: 'удручающий'},
    {enWord: 'consistency', rusWord: 'последовательность'},
    {enWord: 'you can always count on my support', rusWord: 'можешь рассчитывать на мою поддрежку'},
    {enWord: 'he said that he would inform us about it', rusWord: 'он сказал, что сообщит нам об этом'},
    {enWord: 'this story grabbed me from the get-go', rusWord: 'эта история увлекла меня с самого начала'},
    {enWord: 'to compensate travel expenses', rusWord: 'компенсировать расходы на путешествия'},
    {enWord: 'What does this have to do with me?', rusWord: 'Какое отношение это имеет ко мне?'},
    {enWord: 'I wouldn`t be sure about that', rusWord: 'Я бы не был так уверен насчет этого'},
    {enWord: 'equally', rusWord: 'не менее', rusWord2:'также', rusWord3:'одинаково'},
    {enWord: 'to stick', rusWord: 'придерживаться', rusWord2:'воткнуть', rusWord3:'совать'},
    {enWord: 'stick', rusWord: 'палка', rusWord2:'трость', rusWord3:'рычаг'},
    {enWord: 'avid', rusWord: 'страстный', rusWord2:'заядлый', rusWord3:'жадный'},
    {enWord: 'to melt', rusWord: 'таять', rusWord2:'плавить', rusWord3:'растопить'},
    {enWord: 'roughneck', rusWord: 'работяга', rusWord2:'рабочий нефтянник', rusWord3:'рабочий буровик'},
    {enWord: 'weird', rusWord: 'странный', rusWord2:'фатальный', rusWord3:'судьбаносный'},
    {enWord: 'chant', rusWord: 'пение', rusWord2:'сказание', rusWord3:'ода'},
    {enWord: 'meticulous', rusWord: 'дотошный', rusWord2:'тщательный', rusWord3:'скурпулезный'},
    {enWord: 'meticulously', rusWord: 'дотошно', rusWord2:'тщательно', rusWord3:'скурпулезно'},
    {enWord: 'to spur of the moment', rusWord: 'спонтанно', rusWord2:'пришпоривание момента'},
    {enWord: 'breed', rusWord: 'поколение', rusWord2:'потомство'},
    {enWord: 'unraveling', rusWord: 'заспутывание', rusWord2:'разгадка'},
    {enWord: 'enchanting', rusWord: 'очаровательный', rusWord2:'фейерический'},
    {enWord: 'thought-provoking', rusWord: 'содержательный', rusWord2:'наводящий на размышления'},
    {enWord: 'adventurous', rusWord: 'авантюрный', rusWord2:'приключения'},
    {enWord: 'whimsical', rusWord: 'причудливый', rusWord2:'капризный'},
    {enWord: 'grab', rusWord: 'хватать', rusWord2:'схватить'},
    {enWord: 'flood', rusWord: 'наводнение', rusWord2:'потоп'},
    {enWord: 'a long shot', rusWord: 'большой риск', rusWord2:'шансов мало'},
    {enWord: 'reconsider', rusWord: 'пересмотреть', rusWord2:'передумать'},
    {enWord: 'foray', rusWord: 'набег', rusWord2:'налет'},
    {enWord: 'yield', rusWord: 'принести', rusWord2:'дать'},
    {enWord: 'brusqueness', rusWord: 'грубость', rusWord2:'резкость'},
    {enWord: 'references', rusWord: 'ссылки', rusWord2:'рекомендации'},
    {enWord: 'go-getter', rusWord: 'удачливый', rusWord2:'предприимчивый'},
    {enWord: 'unassuming', rusWord: 'скромный', rusWord2:'непритязательный'},
    {enWord: 'boosting', rusWord: 'повышение', rusWord2:'стимулирование'},
    {enWord: 'forcible', rusWord: 'принудительный', rusWord2:'насильственный'},
    {enWord: 'intentionally', rusWord: 'намеренно', rusWord2:'преднамеренно'},
    {enWord: 'intention', rusWord: 'намерение', rusWord2:'замысел'},
    {enWord: 'arrangement', rusWord: 'расположение', rusWord2:'договоренность'},
    {enWord: 'implement', rusWord: 'осуществление', rusWord2:'внедрение'},
    {enWord: 'weirdo', rusWord: 'чудак', rusWord2:'чудик'},
    {enWord: 'to sort out', rusWord: 'уладить', rusWord2:'разобраться'},
    {enWord: 'mess', rusWord: 'беспорядок', rusWord2:'бардак'},
    {enWord: 'restraint', rusWord: 'сдержанность', rusWord2:'ограничение'},
    {enWord: 'whisper', rusWord: 'шорох', rusWord2:'шепот'},
    {enWord: 'parentage', rusWord: 'происхождение', rusWord2:'родство'},
    {enWord: 'interchangeable', rusWord: 'сменный', rusWord2:'взаимозаменяемый'},
    {enWord: 'occasionally', rusWord: 'иногда', rusWord2:'время от времени'},
    {enWord: 'measure', rusWord: 'мера', rusWord2:'измерение'},
    {enWord: 'knuckle', rusWord: 'костяшки', rusWord2:'сустав'},
    {enWord: 'influence', rusWord: 'влияние', rusWord2:'воздействие'},
    {enWord: 'decent', rusWord: 'достойный', rusWord2:'приличный'},
    {enWord: 'addict', rusWord: 'зависимый', rusWord2:'наркоман'},
    {enWord: 'pertinent', rusWord: 'уместный', rusWord2:'соответствующий'},
    {enWord: 'thread', rusWord: 'поток', rusWord2:'нить'},
    {enWord: 'to deduce', rusWord: 'сделать вывод', rusWord2:'предположить'},
    {enWord: 'in a rut', rusWord: 'в рутине', rusWord2:'без прогресса'},
    {enWord: 'arbitrary', rusWord: 'произвольный', rusWord2:'случайный'},
    {enWord: 'on the whole', rusWord: 'в общем', rusWord2:'в целом'},
    {enWord: 'outcome', rusWord: 'результат', rusWord2:'исход'},
    {enWord: 'batch', rusWord: 'порция', rusWord2:'пакет'},
    {enWord: 'lack', rusWord: 'отсутствие', rusWord2:'нехватка'},
    {enWord: 'degrade', rusWord: 'деградировать', rusWord2:'разлагаться'},
    {enWord: 'punch', rusWord: 'удар', rusWord2:'дырокол'},
    {enWord: 'to gain', rusWord: 'получить', rusWord2:'приобрести'},
    {enWord: 'gain', rusWord: 'выгода', rusWord2:'выигрыш'},
    {enWord: 'trace', rusWord: 'след', rusWord2:'отслеживание'},
    {enWord: 'to trace', rusWord: 'проследить', rusWord2:'отследить'},
    {enWord: 'to punch', rusWord: 'ударить', rusWord2:'бить'},
    {enWord: 'a giving man', rusWord: 'щедрый', rusWord2:'добрый человек'},
    {enWord: 'circumstances', rusWord: 'обстоятельства', rusWord2:'условия'},
    {enWord: 'unconscious', rusWord: 'неосознанный', rusWord2:'подсознания'},
    {enWord: 'evidence', rusWord: 'доказательство', rusWord2:'свидетельство'},
    {enWord: 'sneak', rusWord: 'пробраться', rusWord2:'проскользнуть'},
    {enWord: 'sneak out', rusWord: 'улизнуть', rusWord2:'сбежать'},
    {enWord: 'misperception', rusWord: 'заблуждение', rusWord2:'неверное представление'},
    {enWord: 'approach', rusWord: 'подход', rusWord2:'позиция'},
    {enWord: 'thrive', rusWord: 'процветать', rusWord2:'преуспеть'},
    {enWord: 'to approach', rusWord: 'подойти к ..', rusWord2:'обратиться ..'},
    {enWord: 'to grind', rusWord: 'молоть', rusWord2:'измельчить'},
    {enWord: 'grind', rusWord: 'размалывание', rusWord2:'шлифование'},
    {enWord: 'dismissive', rusWord: 'пренебрежительный', rusWord2:'освобождающий'},
    {enWord: 'approachable', rusWord: 'доступный', rusWord2:'отзывчивый'},
    {enWord: 'ease up on', rusWord: 'полегче с...', rusWord2:'не давить на...'},
    {enWord: 'inadmissible', rusWord: 'недопустимый', rusWord2:'неприемлимый'},
    {enWord: 'estimated', rusWord: 'оценочный', rusWord2:'предполагаемый'},
    {enWord: 'He got me into it', rusWord: 'Он вовлек меня в это'},
    {enWord: 'knuckle down', rusWord: 'упираться костяшками', rusWord2:'настроиться на серьезный подход'},
    {enWord: 'to steady', rusWord: 'укреплять', rusWord2:'стабилизировать'},
    {enWord: 'fad', rusWord: 'причуда', rusWord2:'прихоть'},
    {enWord: 'astonishing', rusWord: 'удивительный', rusWord2:'поразительный'},
    {enWord: 'impactful', rusWord: 'впечатляющий', rusWord2:'эффективный'},
    {enWord: 'narrator', rusWord: 'рассказчик', rusWord2:'диктор'},
    {enWord: 'tear-jerker', rusWord: 'душещипательный', rusWord2:'слезливый'},
    {enWord: 'jar', rusWord: 'баночка', rusWord2:'сосуд'},
    {enWord: 'in a nutshell', rusWord: 'по сути', rusWord2:'в двух словах'},
    {enWord: 'anxious', rusWord: 'тревожный', rusWord2:'взволнованный'},
    {enWord: 'rapport', rusWord: 'взаимоотношение', rusWord2:'взаимопонимание'},
    {enWord: 'decline', rusWord: 'сокращение', rusWord2:'снижение', rusWord3:'уменьшение'},
    {enWord: 'share', rusWord: 'доля', rusWord2:'акция', rusWord3:'часть'},
    {enWord: 'endorsement', rusWord: 'одобрение', rusWord2:'утверждение', rusWord3:'принятие'},
    {enWord: 'dash', rusWord: 'тире', rusWord2:'рывок', rusWord3:'бросать'},
    {enWord: 'to complicate', rusWord: 'осложнить', rusWord2:'усложнить', rusWord3:'затруднить'},
    {enWord: 'step up', rusWord: 'активизировать', rusWord2:'наращивать', rusWord3:'усилить'},
    {enWord: 'feature', rusWord: 'особенность', rusWord2:'элемент', rusWord3:'характеристика'},
    {enWord: 'wisely', rusWord: 'мудро', rusWord2:'разумно', rusWord3:'рационально'},
    {enWord: 'hidden gems', rusWord: 'скрытые сокровища', rusWord2:'скрытые достопримечательности', rusWord3:'срытые места (природные)'},
    {enWord: 'handle', rusWord: 'справиться', rusWord2:'разобраться', rusWord3:'обрабатывать'},
    {enWord: 'claim', rusWord: 'претензия', rusWord2:'требование', rusWord3:'жалоба'},
    {enWord: 'off the beaten track', rusWord: 'в глуши', rusWord2:'удаленные места', rusWord3:'спокойные места'},
    {enWord: 'ultimately', rusWord: 'в конечном счете', rusWord2:'в конечном итоге', rusWord3:'в конце концов'},
    {enWord: 'leap', rusWord: 'скачок', rusWord2:'прыжок', rusWord3:'прорыв'},
    {enWord: 'credibility', rusWord: 'авторитет', rusWord2:'доверие', rusWord3:'надежность'},
    {enWord: 'consideration', rusWord: 'рассмотрение', rusWord2:'обсуждение', rusWord3:'изучение'},
    {enWord: 'whilst', rusWord: 'хотя', rusWord2:'пока', rusWord3:'тогда как'},
    {enWord: 'wit', rusWord: 'ум', rusWord2:'остроумие', rusWord3:'сообразительность'},
    {enWord: 'concise', rusWord: 'краткий', rusWord2:'сжатый', rusWord3:'лаконичный'},
    {enWord: 'robust', rusWord: 'надежный', rusWord2:'крепкий', rusWord3:'прочный'},
    {enWord: 'awareness', rusWord: 'осведомленность', rusWord2:'осознание', rusWord3:'понимание'},
    {enWord: 'estimate', rusWord: 'оценка', rusWord2:'смета', rusWord3:'прогноз'},
    {enWord: 'blow', rusWord: 'удар', rusWord2:'передышка', rusWord3:'дурь'},
    {enWord: 'to blow', rusWord: 'дуть', rusWord2:'взрывать', rusWord3:'снести'},
    {enWord: 'blunt', rusWord: 'тупой', rusWord2:'грубый', rusWord3:'прямолинейный'},
    {enWord: 'curt', rusWord: 'резкий', rusWord2:'сжатый', rusWord3:'краткий'},
    {enWord: 'meaner', rusWord: 'злее', rusWord2:'жестче', rusWord3:'грубее'},
    {enWord: 'resolute', rusWord: 'решительный', rusWord2:'твердый', rusWord3:'непоколебимый'},
    {enWord: 'contemptuous', rusWord: 'презрительный', rusWord2:'высокомерный', rusWord3:'пренебрежительный'},
    {enWord: 'down to earth', rusWord: 'приземленный', rusWord2:'реалистичный', rusWord3:'практичный'},
    {enWord: 'frail', rusWord: 'хрупкий', rusWord2:'хилый', rusWord3:'слабый'},
    {enWord: 'hang out', rusWord: 'тусоваться', rusWord2:'болтаться', rusWord3:'зависать'},
    {enWord: 'sustainability', rusWord: 'устойчивость', rusWord2:'стабильность', rusWord3:'экологичность'},
    {enWord: 'suitable', rusWord: 'подходящий', rusWord2:'пригодный', rusWord3:'соответствующий'},
    {enWord: 'around the corner', rusWord: 'за углом', rusWord2:'рукой подать', rusWord3:'на носу'},
    {enWord: 'poignant', rusWord: 'острый', rusWord2:'трогательный', rusWord3:'пронзительный'},
    {enWord: 'put it down', rusWord: 'положить это', rusWord2:'бросить это', rusWord3:'опустить это'},
    {enWord: 'manner', rusWord: 'метод', rusWord2:'манера', rusWord3:'стиль'},
    {enWord: 'diligent', rusWord: 'прилежный', rusWord2:'старательный', rusWord3:'усердный'},
    {enWord: 'earnest', rusWord: 'серьезный', rusWord2:'искренний', rusWord3:'задаток'},
    {enWord: 'arrogant', rusWord: 'высокомерный', rusWord2:'подменный', rusWord3:'наглый'},
    {enWord: 'to reveal', rusWord: 'раскрыть', rusWord2:'выявить', rusWord3:'показать'},
    {enWord: 'culprit', rusWord: 'преступник', rusWord2:'виновный', rusWord3:'обвиняемый'},
    {enWord: 'obscene', rusWord: 'непристойный', rusWord2:'неприличный', rusWord3:'пошлый'},
    {enWord: 'lucrative', rusWord: 'прибыльный', rusWord2:'выгодный', rusWord3:'доходный'},
    {enWord: 'disheartening', rusWord: 'сожаление', rusWord2:'уныние', rusWord3:'разочарование'},
    {enWord: 'explicitly', rusWord: 'конкретно', rusWord2:'однозначно', rusWord3:'недвусмысленно'},
    {enWord: 'to dedicate', rusWord: 'посвещать', rusWord2:'уделять', rusWord3:'выделять'},
    {enWord: 'to pinpoint', rusWord: 'определить', rusWord2:'выявить', rusWord3:'указать'},
    {enWord: 'scenery', rusWord: 'пейзаж', rusWord2:'декорация', rusWord3:'обстановка'},
    {enWord: 'unfolding', rusWord: 'разворачивается', rusWord2:'происходящий', rusWord3:'развертывание'},
    {enWord: 'go off-track', rusWord: 'сбиться с пути', rusWord2:'отклониться от курса', rusWord3:'дать сбой'},
    {enWord: 'bring up', rusWord: 'воспитывать', rusWord2:'вырастить', rusWord3:'поднимать'},
    {enWord: 'invariably', rusWord: 'неизменно', rusWord2:'неизбежно', rusWord3:'во всех случаях'},
    {enWord: 'reservation', rusWord: 'бронирование', rusWord2:'резервирование', rusWord3:'оговорка'},
    {enWord: 'irrelevant', rusWord: 'неуместный', rusWord2:'неактуальный', rusWord3:'несоответствующий'},
    {enWord: 'tangent', rusWord: 'касательная', rusWord2:'другое направление', rusWord3:'тангенс'},
    {enWord: 'inevitable', rusWord: 'неизбежно', rusWord2:'неминуемо', rusWord3:'неотвратимо'},
    {enWord: 'likelihood', rusWord: 'вероятность', rusWord2:'возможность', rusWord3:'шанс'},
    {enWord: 'flop', rusWord: 'провал', rusWord2:'шлепанье', rusWord3:'переброс'},
    {enWord: 'to anticipate', rusWord: 'предвидеть', rusWord2:'прогнозировать', rusWord3:'ожидать'},
    {enWord: 'leap of faith', rusWord: 'прыжок веры', rusWord2:'прыжок в неизвестность', rusWord3:'решительный шаг'},
    {enWord: 'at stake', rusWord: 'на кону', rusWord2:'под угрозой', rusWord3:'в опасности'},
    {enWord: 'to disappear', rusWord: 'исчезнуть', rusWord2:'скрыться', rusWord3:'пропасть'},
    {enWord: 'greed', rusWord: 'жадность', rusWord2:'алчность', rusWord3:'корысть'},
    {enWord: 'stick', rusWord: 'палка', rusWord2:'трость', rusWord3:'клюшка'},
    {enWord: 'to stick', rusWord: 'приклеить', rusWord2:'придерживаться', rusWord3:'воткнуть'},
    {enWord: 'vividly', rusWord: 'наглядно', rusWord2:'ярко', rusWord3:'живо'},
    {enWord: 'attempt', rusWord: 'попытка', rusWord2:'усилия(стремление)', rusWord3:'стремление'},
    {enWord: 'peculiar', rusWord: 'своеобразный', rusWord2:'особый', rusWord3:'специфический'},
]